Выполнил задание 11
htmlacademy-javascript/429567-keksobooking-25 pull request #10
Opened 2022-04-05 21:11 UTC by megokryak

2022-04-06 07:37 UTC, ElseeCCD requested changes

2022-04-06 07:37 UTC, ElseeCCD1 commented on js/generate-ads.js
> +  if (ad.offer.features !== undefined) {
можно оставить просто `if (ad.offer.features) {`

2022-04-06 07:37 UTC, ElseeCCD commented on js/work-form.js
> +  if(address.value.length === 0) {
после if пробел нужен. В поле address, разве, не строка хранится? Можно, наверно, просто проверять на пустую строку?

2022-04-06 07:37 UTC, ElseeCCD commented on js/work-form.js
> +  if(address.value.length === 0) {
Почему по умолчанию перестло проставляться значение поля? Это требование ТЗ https://up.htmlacademy.ru/javascript/25/project/keksobooking#keksobooking-4

2022-04-06 07:37 UTC, ElseeCCD commented on js/util.js
> +  address.value = '';
поле должно быть заполнено всегда. Это требование ТЗ https://up.htmlacademy.ru/javascript/25/project/keksobooking#keksobooking-4

2022-04-06 07:37 UTC, ElseeCCD commented on js/work-form.js
> +form.addEventListener('submit', (evt) => {
валидация минимальной выбранной цены так и не добавлена. Могу выбрать, например, тип жилья "Квартира" и поставить цену 0. Ошибка прилетит только с сервера, на фронте никак не обраатывается

2022-04-06 07:37 UTC, ElseeCCD commented on js/util.js
> +  alertContainer.style.position = 'absolute';
тут, наверно, лучше сделать position fixed, чтобы было видно окошко всегда. В случае с формой, когда на большинстве экранов нужно проскроллить вниз, чтобы её отправить, предупреждение об ошибке не видно

2022-04-06 07:59 UTC, megokryak commented on js/util.js
> +  alertContainer.style.position = 'absolute';
Выполнено

2022-04-06 08:01 UTC, megokryak commented on js/generate-ads.js
> +  if (ad.offer.features !== undefined) {
ок

2022-04-08 11:14 UTC, megokryak commented on js/work-form.js
> +  if(address.value.length === 0) {
ok

2022-04-08 11:14 UTC, megokryak commented on js/util.js
> +  address.value = '';
ok

2022-04-08 12:12 UTC, ElseeCCD approved these changes

2022-04-08 12:12 UTC, merged