Выполнил задание
htmlacademy-javascript/429567-keksobooking-25 pull request #2
Opened 2022-02-21 06:41 UTC by megokryak

2022-02-21 11:48 UTC, ElseeCCD requested changes

2022-02-21 11:48 UTC, ElseeCCD commented on js/main.js
> +}
смотри, у вас указано, что диапазон может быть только положительный. Нужно это учесть тоже )

2022-02-21 11:48 UTC, ElseeCCD commented on js/main.js
> +    max = storage;
ES6 очень классно позволяет менять местами переменные при помощи Destructuring Assignment:
```
[min, max] = [max, min];
```

И всё, не нужны никакие временные переменные. И проблем с линтером не будет. Не забывай, кстати, проверять ошибки линтера перед сдачей домашки. Их обязательно нужно править

2022-02-21 11:48 UTC, ElseeCCD commented on js/main.js
> +    max = storage;
тут, соответсвенно, то же самое, что и выше

2022-02-21 11:48 UTC, ElseeCCD commented on js/main.js
> +//Функция возвращает рандомное целое число из диапазона включительно
а формулы все сам додумывал или взял откуда-то?

2022-02-21 11:48 UTC, ElseeCCD commented on js/main.js
> +}
`getRandomFloat(1.1, 1.2, 1);` возвращает 1.5 . `getRandomFloat(201, 200, 2)` возвращает 201. Надо бы подправить функцию. И опять же, не забыть учесть, что по условиям задачи диапазон может быть только положительный, включая ноль.

2022-02-21 11:54 UTC, megokryak commented on js/main.js
> +//Функция возвращает рандомное целое число из диапазона включительно
3 года назад придумал

2022-02-22 05:31 UTC, ElseeCCD requested changes

2022-02-22 05:31 UTC, ElseeCCD commented on js/main.js
> +  if (min < 0 || max <0)
пробел после `<`

2022-02-22 05:31 UTC, ElseeCCD commented on js/main.js
> +
поправить ошибки линтера

2022-02-22 05:31 UTC, ElseeCCD commented on js/main.js
> +
Всё то же самое, что и выше

2022-02-22 05:31 UTC, ElseeCCD commented on js/main.js
> +console.log(getRandomFloat(200, 201, 2));
Это с прошлой проверки не поправлено. Не должно быть ошибок линтера. Обрати внимание на указание в конце домашки "Чтобы ESLint не ругался на неиспользуемые функции, временно вызовите их по одному разу после объявления."

2022-02-22 07:43 UTC, ElseeCCD approved these changes

2022-02-22 07:43 UTC, merged