Предварительно
htmlacademy-javascript/429567-keksobooking-25 pull request #5
Opened 2022-03-17 07:38 UTC by megokryak

2022-03-18 08:38 UTC, ElseeCCD requested changes

2022-03-18 08:38 UTC, ElseeCCD1 commented on js/generate-ads.js
> +    if (element.offer.title === ''){
Посмотри, пожалуйста, ТЗ. Поле "Заголовок" - обязательное поле, оно не может быть пустым

2022-03-18 08:38 UTC, ElseeCCD1 commented on js/generate-ads.js
> +    if (element.offer.address === '') {
Все остальные поля тоже проверь на обязательность, пожалуйста

2022-03-18 08:38 UTC, ElseeCCD1 commented on js/generate-ads.js
> +      popupFeaturesList.classList.add('hdie');
popupFeaturesList - это у тебя NodeList, ты не можешь ему добавить какой-то класс. Классы добавляем только конкретным DOM-элементам. Например, списку опций: popup__features

2022-03-18 08:38 UTC, ElseeCCD commented on js/generate-ads.js
> +      }
Чтобы избежать лишней портянки switch-case, предлагаю завести отдельный словарик в константах, который будет хранить типы жилья (мы такое называем enum):
```
export const ApartmentType = {
  PALACE: 'Дворец',
  FLAT: 'Квартира',
  HOUSE: 'Дом',
  BUNGALOW: 'Бунгало',
};
```

А тут уже просто обращаться по ключу:
```
adsElement.querySelector('.popup__type').textContent = ApartmentType[element.offer.type.toUpperCase()];
```

2022-03-18 08:38 UTC, ElseeCCD commented on js/generate-ads.js
> +      adsElement.querySelector('.popup__type').classList.add('hdie');
опечатка в названии класса. Должно быть hide. Но не забудь проверить поле на обязательность

2022-03-18 08:38 UTC, ElseeCCD commented on js/generate-ads.js
> +          countRooms = `${element.offer.rooms} комнаты для `;
а почему 3 и 4 не "комнаты"? ))

2022-03-18 08:38 UTC, ElseeCCD commented on js/generate-ads.js
> +      adsElement.querySelector('.popup__text--capacity').textContent = countRooms + countGuests;
заведи для комнат лучше функцию:
```
const getRoomsDeclension = (count) => {
  if (count === 1) {
    return 'комната';
  }
  if (count === 2 || count === 3 || count === 4) {
    return 'комнаты';
  }
  return 'комнат'
}
```

А тут используй так:
```
adsElement.querySelector('.popup__text--capacity').textContent = `${element.offer.rooms} ${getRoomsDeclension(element.offer.rooms)} для ${element.offer.guests} ${element.offer.guests > 1 ? 'гостей' : 'гостя'}`
```

2022-03-18 19:16 UTC, megokryak commented on js/generate-ads.js
> +    if (element.offer.title === ''){
прочитал, спасибо! исправил

2022-03-18 19:16 UTC, megokryak commented on js/generate-ads.js
> +    if (element.offer.address === '') {
прочитал, спасибо! исправил

2022-03-19 11:00 UTC, megokryak commented on js/generate-ads.js
> +      popupFeaturesList.classList.add('hdie');
Сделано. Но добавил для дочерних - мало ли поедет верстка

2022-03-19 11:05 UTC, megokryak commented on js/generate-ads.js
> +      }
отличное решение, спасибо

2022-03-19 11:06 UTC, megokryak commented on js/generate-ads.js
> +      adsElement.querySelector('.popup__type').classList.add('hdie');
исправил. Проверил тип не обязательный

2022-03-19 11:07 UTC, megokryak commented on js/generate-ads.js
> +          countRooms = `${element.offer.rooms} комнаты для `;
затрудняюсь ответить ))))

2022-03-19 11:21 UTC, megokryak commented on js/generate-ads.js
> +      adsElement.querySelector('.popup__text--capacity').textContent = countRooms + countGuests;
Сделано

2022-03-19 11:31 UTC, ElseeCCD approved these changes

2022-03-19 11:31 UTC, merged