Module8 task2
htmlacademy-javascript/429567-keksobooking-25 pull request #8
Opened 2022-03-26 13:11 UTC by megokryak

2022-03-27 07:04 UTC, ElseeCCD requested changes

2022-03-27 07:04 UTC, ElseeCCD1 commented on js/enum.js
>  const ApartmentType = {
ну тогда нужно переименовать. У тебя это уже не enum, у тебя словарик. `apartmentsSettings`, например

2022-03-27 07:04 UTC, ElseeCCD1 commented on js/work-form.js
> +  if (Number(optionGuestsSelect) > Number(optionRoomsSelect) && Number(optionGuestsSelect) !== MAX_GUEST && Number(optionRoomsSelect) !== MIN_ROOM) {
ты уже привёл `optionGuestsSelect` и `optionRoomsSelect` к числу на 57-58 строчках, не нужно этого делать лишний раз. Отсюда надо удалить приведение к числу

2022-03-27 07:04 UTC, ElseeCCD1 commented on js/work-form.js
> +  if (Number(optionGuestsSelect) === MIN_ROOM) {
и отсюда удалить приведение к числу

2022-03-27 07:04 UTC, ElseeCCD1 commented on js/work-form.js
> +  if (Number(optionRoomsSelect) === MAX_GUEST) {
и тут тоже

2022-03-27 07:04 UTC, ElseeCCD1 commented on js/enum.js
> +  PALACE: {
в словаре капсом не пользуемся, обычный camelCase

2022-03-27 07:04 UTC, ElseeCCD1 commented on js/enum.js
> +    MIN_PRICE: 10000
и тут то же самое, обычный camelCase

2022-03-27 07:04 UTC, ElseeCCD1 commented on js/work-form.js
> +  for (let i =0; i < timeOut.options.length; i++) {
нужно пробел добавить после =

2022-03-27 07:04 UTC, ElseeCCD commented on js/work-form.js
> +  const selectElement = timeIn.options[evt.target.options.selectedIndex].value;
у тебя тут не `selectElement` хранится, а значение времени заезда. Так и называй: `timeInValue`

2022-03-27 07:04 UTC, ElseeCCD commented on js/work-form.js
> +  }
чтобы синхронизировать время выезда и заезда, тебе достаточно будет написать так:
```
timeOut.value = timeInValue;
```

2022-03-27 07:04 UTC, ElseeCCD commented on js/work-form.js
> +const changeTimeIn = (evt) => {
тут все те же самые комментарии, что и выше

2022-03-27 07:04 UTC, ElseeCCD commented on js/work-form.js
> +timeIn.addEventListener('change', changeTimeOut);
в предыдущем задании оставляла комментарий на тему того, как нужно именовать слуштаели событий. Поправь, пожалуйста, оба названия

2022-03-27 18:44 UTC, megokryak commented on js/enum.js
>  const ApartmentType = {
Done

2022-03-27 18:46 UTC, megokryak commented on js/work-form.js
> +  if (Number(optionGuestsSelect) > Number(optionRoomsSelect) && Number(optionGuestsSelect) !== MAX_GUEST && Number(optionRoomsSelect) !== MIN_ROOM) {
Done

2022-03-27 18:46 UTC, megokryak commented on js/work-form.js
> +  if (Number(optionGuestsSelect) === MIN_ROOM) {
Done

2022-03-27 18:46 UTC, megokryak commented on js/work-form.js
> +  if (Number(optionRoomsSelect) === MAX_GUEST) {
Done

2022-03-27 18:51 UTC, megokryak commented on js/enum.js
> +  PALACE: {
Done

2022-03-27 18:52 UTC, megokryak commented on js/work-form.js
> +  for (let i =0; i < timeOut.options.length; i++) {
done

2022-03-27 18:52 UTC, megokryak commented on js/work-form.js
> +  const selectElement = timeIn.options[evt.target.options.selectedIndex].value;
Done

2022-03-27 18:55 UTC, megokryak commented on js/work-form.js
> +const changeTimeIn = (evt) => {
Done

2022-03-27 18:55 UTC, megokryak commented on js/work-form.js
> +  }
Done

2022-03-27 18:57 UTC, megokryak commented on js/work-form.js
> +timeIn.addEventListener('change', changeTimeOut);
Done

2022-03-28 07:03 UTC, ElseeCCD requested changes

2022-03-28 07:03 UTC, ElseeCCD commented on js/work-form.js
> +  }
Not done. Тебе не нужен никакой цикл вообще. Только `timeOut.value = timeInValue;`

2022-03-28 07:03 UTC, ElseeCCD commented on js/work-form.js
> +const onChangeTimeIn = (evt) => {
тут то же самое

2022-03-28 07:03 UTC, ElseeCCD commented on js/work-form.js
> +timeIn.addEventListener('change', onChangeTimeOut);
неверно назван обработчик. Ты же слушатель навешиваешь на поле `timeIn`, значит и обработчик должен называться `onChangeTimeIn`

2022-03-28 07:03 UTC, ElseeCCD commented on js/work-form.js
> +timeOut.addEventListener('change', onChangeTimeIn);
тут то же самое

2022-03-28 14:16 UTC, megokryak commented on js/work-form.js
> +  }
now done right)

2022-03-28 14:17 UTC, megokryak commented on js/work-form.js
> +const onChangeTimeIn = (evt) => {
Done

2022-03-28 14:17 UTC, megokryak commented on js/work-form.js
> +timeIn.addEventListener('change', onChangeTimeOut);
Done

2022-03-28 14:17 UTC, megokryak commented on js/work-form.js
> +timeOut.addEventListener('change', onChangeTimeIn);
Done

2022-03-28 14:35 UTC, ElseeCCD approved these changes

2022-03-28 14:35 UTC, merged